### ISSUE TITLE
import geocell isssue

### ISSUE THREAD

**Issue by viji2ks** [kmertol/geocell#4]
>>> import geocell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "geocell/__init__.py", line 1, in <module>
    from .geocell import locate, estimate, api_key, is_multiprocess
  File "geocell/geocell.py", line 30
    print(*args, file=sys.stderr, flush=False, **kwargs)
          ^
SyntaxError: invalid syntax

error while import geo cell

**Comment by jongracecox** [comment]
This looks like you're using an old version of Python that doesn't support the print statement.
